class Service {
  final String? id;
  final String? nom;
  final String creePar;
  final String? description;
  final String categorie;

  Service({
    this.id,
    this.nom,
    required this.creePar,
    this.description,
    required this.categorie,
  });

  // To map data from Supabase to Service object
  factory Service.fromJson(Map<String, dynamic> json) {
    return Service(
      id: json['id'],
      nom: json['nom'],
      creePar: json['creePar'],
      description: json['description'],
      categorie: json['categorie'],
    );
  }

  // To map Service object to a JSON object for Supabase
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};

    // Only include non-null attributes in the JSON
    if (nom != null) {
      data['nom'] = nom;
    }

    data['creePar'] = creePar; // Always included since it's required

    if (description != null) {
      data['description'] = description;
    }

    data['categorie'] = categorie; // Always included since it's required

    // Do not include 'id' if it's auto-generated by Supabase
    return data;
  }
}
